### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Lemonzyy** [qhdwight/voxel-game-rs#6]
Hello @qhdwight , would you mind adding a license to your project?
I also want to implement marching cubes to use it with Bevy and in my opinion it's better not to reinvent the wheel. I've been looking for a long time and I believe you are the first one to share publicly the it's implementation with WGPU and Bevy.

**Comment by qhdwight** [comment]
Yes that's a good idea

**Comment by qhdwight** [comment]
Added GPL V3 for now

**Comment by Lemonzyy** [comment]
Thanks you very much :)
